# generated by datamodel-codegen:
#   filename:  CategorizedIngredients.json
#   timestamp: 2023-12-01T08:13:14+00:00

from __future__ import annotations

from typing import Any, Dict, List

from pydantic import BaseModel, Field


class CategorizedIngredients(BaseModel):
    food_groups: Dict[str, Any] = Field(..., title='Food Groups')
    potential_dish_types: List = Field(..., title='Potential Dish Types')
