# generated by datamodel-codegen:
#   filename:  IngredientAnalysis.json
#   timestamp: 2023-12-01T08:55:51+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel, Field


class IngredientAnalysis(BaseModel):
    """
    A structured analysis of the ingredients that includes potential cuisine types, dietary restrictions, and flavor profiles.
    """

    cuisine_types: List[str] = Field(
        ...,
        description='Possible cuisine types that can be made with the ingredients.',
        title='Cuisine Types',
    )
    dietary_restrictions: List[str] = Field(
        ...,
        description='Any dietary restrictions that apply to the ingredients, such as gluten-free or vegan.',
        title='Dietary Restrictions',
    )
    flavor_profiles: List[str] = Field(
        ...,
        description='The general flavor profiles that can be achieved with the ingredients, like savory, sweet, spicy, etc.',
        title='Flavor Profiles',
    )
