# generated by datamodel-codegen:
#   filename:  IngredientCategories.json
#   timestamp: 2023-11-30T10:46:57+00:00

from __future__ import annotations

from typing import Any

from pydantic import BaseModel


class Model(BaseModel):
    __root__: Any
