# generated by datamodel-codegen:
#   filename:  StructuredQuery.json
#   timestamp: 2023-11-30T08:26:33+00:00

from __future__ import annotations

from typing import Dict, List

from pydantic import BaseModel, Field


class StructuredQuery(BaseModel):
    search_terms: List[str] = Field(
        ...,
        description='A list of key terms extracted from the user input that are relevant to the search.',
        title='Search Terms',
    )
    query_parameters: Dict[str, str] = Field(
        ...,
        description='A dictionary of parameters that will be used to structure the query for the database.',
        title='Query Parameters',
    )
