# generated by datamodel-codegen:
#   filename:  SchemaActionOutline.json
#   timestamp: 2023-11-30T08:26:59+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class SchemaActionOutline(BaseModel):
    content: str = Field(
        ...,
        description='The python function for performing the desired task. \n                          This should always contain a keyword argument called `role` of type `Role` that defaults to None. ',
        title='Content',
    )
